language: bash

services:
  - docker

env:
  global:
    - GRPC_HEALTH_PROBE=galleog/grpc-health-probe

script:
  - docker build -t $GRPC_HEALTH_PROBE:alpine ./alpine
  - docker build -t $GRPC_HEALTH_PROBE:slim ./slim

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - docker push $GRPC_HEALTH_PROBE
