language: bash

services:
  - docker

env:
  global:
    - secure: Zqso5jholfBwSXE51mC2szmhg0z61UfV9QwTwJzMo+fFrRlxnAokeP0tLjSW7WTYLHVHXcs4pNLrgk3UrZgVnoki4sJ7qgqJA3n1zqFwT9VVF4SStKT2xeLMHvAtJmXpV3Ne3dLp1TGWRaz9p3/uS6dSnslWL7EgRgZ7KLl12EOP2hteVVuMPMJTajt3Ax1TxS0jayYXICqUdLVciDdHGlN3rp4RL3zKBOsEroQEQI0cwNRW/nXdYQJUzOEdjgtBUQ9ByB1GB/j8v21h8QjfV2l/iBGcA2QarJkU9DbXWXCwND7YDJkyqLH19nt/WoHkci+u2EVwcrtXp11gZi2UySZUJrigWt7Rd/tCPbQbXCQ5hL+lUo8StydyZkwSE6brexCpghGU9lp7cPEb8yrHUbUvZJ6e/RIq6PZoUxZX9au1m0wL4pvoWVZyRn/D1RsjeTW4aITpg4EjudV6E+LxWc532L1JtSohZcrW4VWqIkj/pDeDF+WgHePvTkpn8Acv9HTCBuUZP0PkQO4aQuIKM7vwnhRzyemkHD1JUb2n9QDFLcSppYrMrkMdunUR80KabNxvhC0x0Go2LXOeiVlsi+5HfrYbGQgoKr3li0V9pv2oCeoFPHozqfIX+7VopGoKHljL9ccto7bTLXc8vCSvezaxaCQbDry3S3FS/0kLeog=
    - COMMIT=${TRAVIS_COMMIT::7}
    - GRPC_HEALTH_PROBE=galleog/grpc-health-probe

script:
  - docker build -t $GRPC_HEALTH_PROBE:$COMMIT ./

after_success:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
  - docker tag $GRPC_HEALTH_PROBE:$COMMIT $GRPC_HEALTH_PROBE:$TAG
  - docker push $GRPC_HEALTH_PROBE
