language: bash

services:
  - docker

env:
  global:
    - secure: "asSqroBW2cAgRMUTYnNfZkTQUcYpaXDWnfATHEjG+cLCWXZxPsPYcm8tZt+Vy/z+w5ekAaMV6XtZn6HOqZIYb2vOrGqgZ176V2IHkr9gy4h2FkvReJ9HBQG5OB6cLtGmt0FRDIYhgU13UGXXHwcWF4GjexKqnTfs4ky4qGJSIWjkyFd39OrM43SoQjhdfPentLrojJlK5mdykNIMYdn+RfzuHYP8QpLcjOa6akpx0T/kVdn337XY5i/bspVMiIe+zspmz8CjtzXP4j0sY55FrFxIvxb4iF0xB1SwOvL4kWdisEcv2v9ztBIb8M5zQcndTZ+MWh/r9RSrTRIMyg5PfcDo/G9JZeD82U+ZxWh9TIe1I9DTedHD98MZ5vUjIDRS/U0pR41W3KiXdK5GVfTVeTbZjZuNwilGnnu8uolD5c9M+YuevsdMptEDuRXQjHQGA/btxAn7q+ennnndDgjS0WCsreEg6sftK4iP4Lp25anPsQLNmQ8UDPHX1GYfLj19ExywEbTTp7jYxPYy/YAReD+F/zIzBeDO7qsCQNddDS0g/L8Iom6X/UAu12eMN3CIH0HPsx+zKCRfp+dyeD7xTXu1718l57jPFw9Fl1qzfxw37StyEN+g4WWjIa+LZsOgpR7NLOBh3oMriSkJombHSWPPYyjrS6kuI5gdh1TtzlQ="
    - COMMIT=${TRAVIS_COMMIT::7}
    - GRPC_HEALTH_PROBE=galleog/grpc-health-probe

script:
  - docker build -t $GRPC_HEALTH_PROBE:$COMMIT ./

after_success:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
  - docker tag $GRPC_HEALTH_PROBE:$COMMIT $GRPC_HEALTH_PROBE:$TAG
  - docker push $GRPC_HEALTH_PROBE
