language: bash

services:
  - docker

env:
  global:
    - secure: "UI0Vz0IF0YFV6DR/IjucyiwRzofI0vanNQ3pFypzigrjkDa89WG0jEAbvLRIMhlrus0DxDSIMzetsZKhyiZL7+CMjwZPm6lOiDBr0pVPEzeEtYJC6zr+yrw59y7zOuBXBqB0euNsehaWdl8AII3EbkynsFTJC3xHEZgBvMiWfmhPjQA2xIEt4Kj19oy7E9o57XZ2wasrDq/BXhaWs6ISl+yi8aJhr7yK0ARkzeI11hElfl2kq2zsOLSBz/aA4nv3QnkqR/WL+2SHNbkYwQzn/H9LzUkf+Bj5tDy+/yRVlq5GgpAc4SjuS3600L9zg9i0Sfe+ZOlmN0CGYJcgDqnayDBASBuCn09Sk/rdFkMOKUIkCcUcrPIJ0KfiRMTyTh7+Fp8hxiVFUY4L052QtmwCP8f4QDwaAhyxuzU1q+m4OYwqJFRfdodb0vah889s3+ckbwEnS4kvHXJ3gh5GVYKu4lQUHaGshcd9/yPkO+uHhuy0uVcigR5lZFpVlPbuR31jjUx/iOXKXwuoX+C2J+Lj/ntHxNZEoiB6DU94o8Jb6w3V6UPyTYbOC3DQyypfVyUz2Z4MxpiekdjEUSjq1jR6ihdUVyKujfxQEe9A15MnIHIey1JztLwYJyTCDg6F47rX5Co4DB13uNjZ41Svani1S5F7Nyv9TdPtVmc4bYP2b4c="
    - COMMIT=${TRAVIS_COMMIT::7}
    - GRPC_HEALTH_PROBE=galleog/grpc-health-probe

script:
  - docker build -t $GRPC_HEALTH_PROBE:$COMMIT ./

after_success:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
  - docker tag $GRPC_HEALTH_PROBE:$COMMIT $GRPC_HEALTH_PROBE:$TAG
  - docker push $GRPC_HEALTH_PROBE
