language: bash

services:
  - docker

env:
  global:
    - secure: upuFbBvMhs9R67uBB2B8W5Syrt6qvOsrG9PE8CvRYtL3kRBA5Nm5MXRx3oiRXcOhHn3tb8/SN5k9xHbUhxhxC7rgH9XTqtYS5H087fIrX0L75hIbo302BwYaHJFyQvaBxrR6Ua1hXFf/SaS/u0UII1TyIPFduu9h44Fdrk/4xyc+8eY6OdAbnpYOTdCY0ZD5py9O+830MEFqbyRV6vaU2iNcaqEIstz9a7pZGCm6nVpk9Ze8CvpFjzWCS09Ei27rT+1nlRQa8kAhPIm1hmlw2765mM53BKjoqHIngf2pp/P3Qu57O+T8JUXSWnKuHGVJy1NnE+dx2BhJmODsvUL4XSnnzUMjcLw8LK3cbMjG3VI6VxSlviHXQdY0As5pxbzU+Kst4lpS2Y+dRkrvKE387h8FR3XfyXd92t46uscf+5l6OarEYPaoDHDhDEh4mQSJln3MbmigSq+AH//Yo4HQ15CWv5PDYBO+77nydxIfztGO2nDaLsY48hhhuVP6jsPoNHqmBZO1Rx66OYU6hyzWEDQec6NscPjfMFt/j3Mvp9wEdpuPsDwrh8DD+EBj/U4mh+7QinA7PTNXBBImNPXMs33gly3FOSRatWmwSt2DLRFes6fhvLTsoZjjdFL4TcKTXJTNqs24rEC/563LtJUvYeL3pfg/dwWMxlElB0RLYn8=
    - COMMIT=${TRAVIS_COMMIT::7}
    - GRPC_HEALTH_PROBE=galleog/grpc-health-probe

script:
  - docker build -t $GRPC_HEALTH_PROBE:$COMMIT ./

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
  - docker tag $GRPC_HEALTH_PROBE:$COMMIT $GRPC_HEALTH_PROBE:$TAG
  - docker push $GRPC_HEALTH_PROBE
