language: bash

services:
  - docker

env:
  global:
    - secure: EO+1kHtMhyBUqQvRE3WXXs1QtJke/WuyneZkjT6gtX/x4OU/w79HcNOaLTnmlsffe5D6LqiRzNLEKb1vHHnbBANfR2/3BHAnf6J1uk10LWQYN835xGAayoR5DAw+YoXIpZTJXb8DbTUxuIMqpQ48lH6QYOMugfIxC6JJcCZ5pWpKiNv1rbgWx5KDBuv6Xis0o6u/nTI5EPeeMgJ81LSvifrgpV8NPxPkRo+CyvPfDoOVmfxosxagYyBJvDxTbtkmBtZHaNsuene/08og1GTmXJV+6zssl4yFWObupbFNLsDOqK20e0FXBeuVvzpHOzWvlPEZTCu02mYu80LqOAkzCTy230YdYx8qy3yEiXo8NmbqUEJJtxrcdx2PIETj2YR4qR4J2VuFvBZbBvKrkI8qyE/BvD+KwOc6DIC1qrIW6QiksFQoqADrw478fIl6YPcMRZWaBEXGH1JqgfQVmrXYoAOKjIP2l9w/fMuoAxswrOtSZYJEkUp2RPunm/BmrMdnF5R3pfytS58QLMVn3VHbMork801vLPX6tRr90foazut9iPP0qumbX7hwMvi9JUf68952jWLLuY0MXIVct2mnm4tZ/3F/cJtMiLfAHlUwSSd7ryzPT1JjTVYQ+Zsv2kR+sxDcj8DEKCXaZpOky8xG+hK4R0yIFyZd51w3xk10hYk=
    - COMMIT=${TRAVIS_COMMIT::7}
    - GRPC_HEALTH_PROBE=galleog/grpc-health-probe

script:
  - docker build -t $GRPC_HEALTH_PROBE:$COMMIT ./

after_success:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
  - docker tag $GRPC_HEALTH_PROBE:$COMMIT $GRPC_HEALTH_PROBE:$TAG
  - docker push $GRPC_HEALTH_PROBE
