language: bash

services:
  - docker

env:
  global:
    - secure: "e/wHwD20Cx/nItz1M2Ax94SJt8Gk7fNbZHL7Vz8iwRRZ6jbRiN8wDplkZnsqr5Pw8xu14cT2yuTkdqmy7ya1EtIzy+E7mnCvbI1gL07Q7DHlTmT7b6Cv1XNKGNLOvwFSHJkDQcN6Tgzxsfx7hCBj6KEtyEhjYMTcZrUs1XV135PMrpv0tCdnR8z1uqrB543gT2mWOYJOXHaadzcQzAXc59JbMaT5GfRJCytuh0R21uudUJGmXBmCKRTZ57E8jSMXkjrXWtp/t8YgRxM0M5qfTjqYwjs8bKEw4942D4/M/taD62jq4NGSDpadOv11JjK6rKw21TuunwxD4dZA7LBz1fRAc12Zq4SP+iGeVqxj+QDOw9oh1bXTEvo0GyBSodpJK0pcGQJlQ9mp8X8jSPgIn9DHZUnAkCgA41P2msZICo7eqpzf9ZmFr6sxV0G/gPuISFAQOjbyFdKV1McskLpz33pdj7p8nGG2AX3AEQ09r4WV1cD0CxWdebnuHofAfVdVHCAcnHLv+wu2oo5Dh/vRnhzo7ujWq1cZ006r7Wsdf9LS1SZp8UzhvDilJQRRtLKSxUYTR8bM55pNBS9s3zNs+Wt6YrIFXOSGBfJaPXNs70AkU1nlb4OVI3s+9VDIDcgaSEeBqqd2fDojO2C1WVoZmifaq4tg9qaEQx0UkSXCxDo="
    - COMMIT=${TRAVIS_COMMIT::7}
    - GRPC_HEALTH_PROBE=galleog/grpc-health-probe

script:
  - docker build -t $GRPC_HEALTH_PROBE:$COMMIT ./

after_success:
  - echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)
  - docker tag $GRPC_HEALTH_PROBE:$COMMIT $GRPC_HEALTH_PROBE:$TAG
  - docker push $GRPC_HEALTH_PROBE
